# Generated by Django 6.0.3 on 2026-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestGenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('code', 'Code'), ('api', 'API Endpoint'), ('story', 'User Story')], max_length=20)),
                ('test_mode', models.CharField(choices=[('black_box', 'Black Box'), ('white_box', 'White Box')], default='black_box', max_length=20)),
                ('raw_input', models.TextField()),
                ('generated_pytest', models.TextField(blank=True)),
                ('generated_junit', models.TextField(blank=True)),
                ('generated_jest', models.TextField(blank=True)),
                ('quality_score', models.FloatField(null=True)),
                ('scores', models.JSONField(null=True)),
                ('coverage_report', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
